# Generated by Django 3.2.3 on 2021-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cliente_colaborador_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='documento_identidad',
            new_name='dni',
        ),
    ]
